const main = () => {
  try {
    teste;
  } catch (error) {
    console.error(`Erro detectado: \n\n${error}`);
  }
};

main();
